[package]
name = "ft_linear_regression"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
plotters = "0.3"
[[bin]]
name = "train"
path = "src/bin/train.rs"
